Project_Solpac_Web/Models/ErrorViewModel.cs
namespace Project_Solpac_Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Project_Solpac_Web/Models/Request.cs
using System.ComponentModel.DataAnnotations;

namespace Project_Solpac_Web.Models
{
    public class Request
    {

        [Key]
        public int RequestNo { get; set; }
        public DateTime RequestDate { get; set; } = DateTime.Now;
        public string? RequestPerson { get; set; }
        public string? Partner { get; set; }
        public string? EndUser { get; set; }
        public string? SoftwareProduct { get; set; }
        public string? ProgramName { get; set; }
        [Required]
        public string? CurrentSituation { get; set; }
        [Required]
        public string? ContentsOfRequest { get; set; }
        [Required]
        public string? CorrectSituation { get; set; }
        public string? Contact { get; set; }
    }
}

Project_Solpac_Web/Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace Project_Solpac_Web.Models
{
    public class User
    {
        [Key]
        public int Id { get; set; }

        //[Required(ErrorMessage = "Name is required")]
        public string? Name { get; set; }

        ///[Required(ErrorMessage = "Email is required")]
        //[EmailAddress(ErrorMessage = "Invalid email address")]
        public string? Email { get; set; }

        //[Required(ErrorMessage = "Password is required")]
        public string? Password { get; set; }

        //[Required(ErrorMessage = "Phone number is required")]
        //[RegularExpression(@"^\d{10}$", ErrorMessage = "Phone number must have 10 digits")]
        public string? Phone { get; set; }
    }
}

Project_Solpac_Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Project_Solpac_Web.Data;
using Project_Solpac_Web.Models;
using System;
using System.Diagnostics;
using System.Reflection.Metadata;

namespace Project_Solpac_Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly SolpacClientDbContext _db;

        public HomeController(SolpacClientDbContext db)
        {
            _db = db;
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }

        //Login
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(string username, string password)
        {
            var User = _db.Users.FirstOrDefault(u=> u.Name == username);
            if (User != null && User.Name == username && User.Password == password)
            {
                return View();
            }
            return RedirectToAction("Index");  
        }

        [HttpPost]
        public IActionResult Register(User user)
        {
            if (ModelState.IsValid)
            {
                _db.Users.Add(user);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("Register");
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Project_Solpac_Web/Controllers/RequestController.cs
using Microsoft.AspNetCore.Mvc;
using Project_Solpac_Web.Data;
using Project_Solpac_Web.Models;

namespace Project_Solpac_Web.Controllers
{
    public class RequestController : Controller
    {
        private readonly SolpacClientDbContext _db;

        public RequestController(SolpacClientDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Request> objRequestList = _db.Requests;
            return View(objRequestList);
        }

        //Get
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Request obj)
        {
            _db.Requests.Add(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Project_Solpac_Web/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Project_Solpac_Web.Data;
using Project_Solpac_Web.Models;

namespace Project_Test.Controllers
{
    public class UserController : Controller
    {
        private readonly SolpacClientDbContext _db;

        public UserController(SolpacClientDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<User> objUserList = _db.Users;
            return View(objUserList);
        }

        //Get
        public IActionResult Create()
        {
            return View();
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(User obj)
        {
            _db.Users.Add(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        //Get
        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            var userFromDb = _db.Users.Find(id);
            var userFromDbFirst = _db.Users.FirstOrDefault(x => x.Id == id);
            var userFromDbSingle = _db.Users.SingleOrDefault(x => x.Id == id);
            if(userFromDb == null)
            {
                return NotFound();
            }
            return View(userFromDb);
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(User obj)
        {
            _db.Users.Update(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Project_Solpac_Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h2>Welcome to Tikkit</h2>

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
}

<form method="post" asp-controller="Home" asp-action="Login">
    <div class="form-group">
        <label for="username">Username:</label>
        <input type="text" id="username" name="Username" class="form-control" required>
    </div>
    <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" id="password" name="Password" class="form-control" required>
    </div>
    <button type="submit" class="btn btn-primary">Login</button>

    <div class="text-center">
        <p>Don't have an account? <a href="/Home/Register">Register</a></p>
    </div>
</form>

Project_Solpac_Web/Views/Home/Login.cshtml
@{
    ViewData["Title"] = "Login";
}

<h1>Đăng nhập thành công</h1>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Request" asp-action="Index">Request</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

Project_Solpac_Web/Views/Home/Register.cshtml
@{
    ViewData["Title"] = "Register";
}

<h2>Register</h2>

<form method="post" action="/Home/Register">
    <div class="form-group">
        <label for="name">Name:</label>
        <input type="text" id="name" name="Name" class="form-control" required>
    </div>
    <div class="form-group">
        <label for="email">Email:</label>
        <input type="email" id="email" name="Email" class="form-control" required>
    </div>
    <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" id="password" name="Password" class="form-control" required>
    </div>
    <div class="form-group">
        <label for="phone">Phone Number:</label>
        <input type="tel" id="phone" name="PhoneNumber" class="form-control" required>
    </div>
    <button type="submit" class="btn btn-primary">Register</button>
</form>

Project_Solpac_Web/Views/Request/Create.cshtml
@model Request

<form method="post">
    <div class="border p-3 m-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Create new Request
            </h2>
        </div>
        <div class="mb-3">
            <label asp-for="RequestPerson">Request Person</label>
            <input asp-for="RequestPerson" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Partner">Partner</label>
            <input asp-for="Partner" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="EndUser">End User</label>
            <input asp-for="EndUser" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="SoftwareProduct">Software Product</label>
            <input asp-for="SoftwareProduct" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="ProgramName">Program Name</label>
            <input asp-for="ProgramName" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="CurrentSituation">Current Situation</label>
            <input asp-for="CurrentSituation" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="ContentsOfRequest">Contents of Request</label>
            <input asp-for="ContentsOfRequest" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="CorrectSituation">Correct Situation</label>
            <input asp-for="CorrectSituation" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Contact">Contact</label>
            <input asp-for="Contact" class="form-control" />
        </div>

        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="Request" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to request list
        </a>
    </div>
</form>

Project_Solpac_Web/Views/Request/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Requests</h1>
<br />

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Request List</h2>
        </div>

        <div class="col-6 text-end">
            <a asp-controller="Request" asp-action="Create" class="btn btn-primary">Create new request</a>
        </div>
    </div>
</div>

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Request N0
            </th>
            <th>
                Request Date
            </th>
            <th>
                Request Person
            </th>
            <th>
                Partner
            </th>
            <th>
                End User
            </th>
            <th>
                Software Product
            </th>
            <th>
                Program Name
            </th>
            <th>
                Current Situation
            </th>
            <th>
                Content of Request
            </th>
            <th>
                Correct Situation
            </th>
            <th>
                Contact
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            <tr>

                <td width="10%">
                    @obj.RequestNo
                </td>

                <td width="10%">
                    @obj.RequestDate
                </td>

                <td width="10%">
                    @obj.RequestPerson
                </td>

                <td width="10%">
                    @obj.Partner
                </td>

                <td width="10%">
                    @obj.EndUser
                </td>

                <td width="10%">
                    @obj.SoftwareProduct
                </td>

                <td width="10%">
                    @obj.ProgramName
                </td>

                <td width="10%">
                    @obj.CurrentSituation
                </td>

                <td width="10%">
                    @obj.ContentsOfRequest
                </td>

                <td width="10%">
                    @obj.CorrectSituation
                </td>

                <td width="10%">
                    @obj.Contact
                </td>
            </tr>
        }
    </tbody>
</table> 

Project_Solpac_Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project_Solpac_Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Project_Solpac_Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Project_Solpac_Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Project_Solpac_Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Project_Solpac_Web/Views/User/Create.cshtml
@model User

<form method="post">
    <div class="border p-3 m-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Create new User
            </h2>
        </div>
        <div class="mb-3">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Email">Email</label>
            <input asp-for="Email" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Password">Password</label>
            <input asp-for="Password" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Phone">Phone number</label>
            <input asp-for="Phone" class="form-control" />
        </div>

        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="User" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to user list
        </a>
    </div>
</form>

Project_Solpac_Web/Views/User/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
}

@model User

<form method="post" asp-action="Edit">
    <div class="border p-3 m-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Edit an User
            </h2>
        </div>
        <div class="mb-3">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Email">Email</label>
            <input asp-for="Email" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Password">Password</label>
            <input asp-for="Password" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Phone">Phone number</label>
            <input asp-for="Phone" class="form-control" />
        </div>

        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="User" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to user list
        </a>
    </div>
</form>

Project_Solpac_Web/Views/User/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Chỉnh sửa người dùng</h1>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">User List</h2>
        </div>

        <div class="col-6 text-end">
            <a asp-controller="User" asp-action="Create" class="btn btn-primary">Create new user</a>
        </div>
    </div>
</div> 

<br />

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Username
            </th>
            <th>
                Email
            </th>
            <th>
                Password
            </th>
            <th>
                Phone Number
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td width="25%">
                    @obj.Name
                </td>

                <td width="25%">
                    @obj.Email
                </td>
                
                <td width="25%">
                    @obj.Password
                </td>

                <td width="25%">
                    @obj.Phone
                </td>

                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="User" asp-action="Edit" asp-route-id="@obj.Id">Edit</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table> 